src/KmBundle/Entity/Branch.php
<?php

namespace KmBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Branch
 *
 * @ORM\Table(name="branch")
 * @ORM\Entity(repositoryClass="KmBundle\Repository\BranchRepository")
 */
class Branch
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     * @ORM\Column(name="idSynchrone", type="string", nullable=true, unique=true)
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $idSynchrone;
    
    /**
     * @var float
     *
     * @ORM\Column(name="flySaleAmount", type="float", nullable=true)
     */
    private $flySaleAmount;
    
    /**
     * @var float
     *
     * @ORM\Column(name="flyProfitAmount", type="float", nullable=true)
     */
    private $flyProfitAmount;
    
    /**
     * @var float
     *
     * @ORM\Column(name="flyExpenditureAmount", type="float", nullable=true)
     */
    private $flyExpenditureAmount;
    
    /**
     * @var float
     *
     * @ORM\Column(name="flyBalanceAmount", type="float", nullable=true)
     */
    private $flyBalanceAmount;
    
    /**
     * @ORM\OneToMany(targetEntity="UserBundle\Entity\User", mappedBy="branch")
     */
    private $users;
    
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
    
    /**
     * @ORM\OneToMany(targetEntity="TransactionBundle\Entity\Stock", mappedBy="branch")
     */
    private $stocks;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;
    
    /**
     * @ORM\OneToMany(targetEntity="TransactionBundle\Entity\STransaction", mappedBy="branch")
     */
    private $stransactions;
    
    /**
     * @ORM\OneToMany(targetEntity="KmBundle\Entity\Expenditure", mappedBy="branch")
     */
    private $expenditures;

    public function __construct() {
        $this->setCreatedAt(new \DateTime("now"));
    }
    
    public function __toString() {
	if($this->name){
	    return $this->name;
	}        
	return 'New Branch';
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Branch
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Branch
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Add stransaction
     *
     * @param \TransactionBundle\Entity\STransaction $stransaction
     *
     * @return Branch
     */
    public function addStransaction(\TransactionBundle\Entity\STransaction $stransaction)
    {
        $this->stransactions[] = $stransaction;

        return $this;
    }

    /**
     * Remove stransaction
     *
     * @param \TransactionBundle\Entity\STransaction $stransaction
     */
    public function removeStransaction(\TransactionBundle\Entity\STransaction $stransaction)
    {
        $this->stransactions->removeElement($stransaction);
    }

    /**
     * Get stransactions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStransactions()
    {
        return $this->stransactions;
    }

    /**
     * Add expenditure
     *
     * @param \KmBundle\Entity\Expenditure $expenditure
     *
     * @return Branch
     */
    public function addExpenditure(\KmBundle\Entity\Expenditure $expenditure)
    {
        $this->expenditures[] = $expenditure;

        return $this;
    }

    /**
     * Remove expenditure
     *
     * @param \KmBundle\Entity\Expenditure $expenditure
     */
    public function removeExpenditure(\KmBundle\Entity\Expenditure $expenditure)
    {
        $this->expenditures->removeElement($expenditure);
    }

    /**
     * Get expenditures
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getExpenditures()
    {
        return $this->expenditures;
    }

    /**
     * Get expenditure value
     * @return integer
     */
    public function getExpendituresAmount()
    {
        //Get all the expenditure related to the given branch
        $expenditures = $this->getExpenditures();
        $total = 0.00;
        foreach ($expenditures as $exp){
            $total = $total + $exp->getAmount();
        }

        return $total;
    }

    /**
     * Add stock
     *
     * @param \TransactionBundle\Entity\Stock $stock
     *
     * @return Branch
     */
    public function addStock(\TransactionBundle\Entity\Stock $stock)
    {
        $this->stocks[] = $stock;

        return $this;
    }

    /**
     * Remove stock
     *
     * @param \TransactionBundle\Entity\Stock $stock
     */
    public function removeStock(\TransactionBundle\Entity\Stock $stock)
    {
        $this->stocks->removeElement($stock);
    }

    /**
     * Get stocks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStocks()
    {
        return $this->stocks;
    }

    /**
     * Add user
     *
     * @param \UserBundle\Entity\User $user
     *
     * @return Branch
     */
    public function addUser(\UserBundle\Entity\User $user)
    {
        $this->users[] = $user;

        return $this;
    }

    /**
     * Remove user
     *
     * @param \UserBundle\Entity\User $user
     */
    public function removeUser(\UserBundle\Entity\User $user)
    {
        $this->users->removeElement($user);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->users;
    }
    
    /**
     * 
     * @return list of stocks in alert zone
     */
    public function getAlertStocks()
    {
        $alertLevels = array();
        
        foreach($this->getStocks() as $stock){
            if($stock->getAlertLevel() >= $stock->getValue() && $stock->isTracked()){
                $alertLevels[] = $stock;
            }
        }
        
        return $alertLevels;
    }

    /**
     * Set flySaleAmount
     *
     * @param float $flySaleAmount
     *
     * @return Branch
     */
    public function setFlySaleAmount($flySaleAmount)
    {
        $this->flySaleAmount = $flySaleAmount;

        return $this;
    }

    /**
     * Get flySaleAmount
     *
     * @return float
     */
    public function getFlySaleAmount()
    {
        return $this->flySaleAmount;
    }

    /**
     * Set flyProfitAmount
     *
     * @param float $flyProfitAmount
     *
     * @return Branch
     */
    public function setFlyProfitAmount($flyProfitAmount)
    {
        $this->flyProfitAmount = $flyProfitAmount;

        return $this;
    }

    /**
     * Get flyProfitAmount
     *
     * @return float
     */
    public function getFlyProfitAmount()
    {
        return $this->flyProfitAmount;
    }

    /**
     * Set flyExpenditureAmount
     *
     * @param float $flyExpenditureAmount
     *
     * @return Branch
     */
    public function setFlyExpenditureAmount($flyExpenditureAmount)
    {
        $this->flyExpenditureAmount = $flyExpenditureAmount;

        return $this;
    }

    /**
     * Get flyExpenditureAmount
     *
     * @return float
     */
    public function getFlyExpenditureAmount()
    {
        return $this->flyExpenditureAmount;
    }

    /**
     * Set flyBalanceAmount
     *
     * @param float $flyBalanceAmount
     *
     * @return Branch
     */
    public function setFlyBalanceAmount($flyBalanceAmount)
    {
        $this->flyBalanceAmount = $flyBalanceAmount;

        return $this;
    }

    /**
     * Get flyBalanceAmount
     *
     * @return float
     */
    public function getFlyBalanceAmount()
    {
        return $this->flyBalanceAmount;
    }

    /**
     * Set idSynchrone
     *
     * @param integer $idSynchrone
     *
     * @return Branch
     */
    public function setIdSynchrone($idSynchrone)
    {
        $this->idSynchrone = $idSynchrone;

        return $this;
    }

    /**
     * Get idSynchrone
     *
     * @return integer
     */
    public function getIdSynchrone()
    {
        return $this->idSynchrone;
    }
}

src/KmBundle/Controller/DefaultController.php
<?php

namespace KmBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Hackzilla\BarcodeBundle\Utility\Barcode;

class DefaultController extends Controller
{
    public function synchronizerAction()
    {
        $synchronizerHandler = $this->get('km.synchronizer_handler');
        $synchronizerHandler->sart();
    }

    public function frontAction()
    {
        //when logout, goes to the login page
        //Get the authorization checker
        $authChecker = $this->get('security.authorization_checker');
        if(!$authChecker->isGranted("ROLE_SELLER")){
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
        
        return $this->render('KmBundle:Default:front.html.twig');
    }
    
    public function alertStockAction()
    {
        //Get all the branch
        $em = $this->getDoctrine()->getManager();
        $branches = $em->getRepository('KmBundle:Branch')->findAll();
        
        return $this->render('KmBundle:Default:alert_stock.html.twig', array('branches' => $branches));
    }
    
    public function stockUpdateAction()
    {
        //Get all the branch
        $em = $this->getDoctrine()->getManager();
        //Get the branch
        $branch = $this->getUser()->getBranch();
        //Get all the updated stock
        $stocked = $em->getRepository('TransactionBundle:Stock')->getStocked($branch);
        $destocked = $em->getRepository('TransactionBundle:Stock')->getDestocked($branch);
        //Get all the CanceledSTransactionNotification for $branch
        $canceledSTransactions = $em->getRepository('TransactionBundle:CanceledSTransaction')
                ->findBy(array('branchId' => $branch->getId()));
        
        return $this->render('KmBundle:Default:stock_update.html.twig',
                array('stocked' => $stocked, 'destocked' => $destocked,
                      'canceledSTransactions' => $canceledSTransactions));
    }
    
    public function dashboardAction()
    {
        //Get the statistic handler service
        $statisticHandler = $this->get('km.statistic_handler');
        //Get the entity manager
        $em = $this->getDoctrine()->getManager();
        //Get all the branches
        $branches = $em->getRepository('KmBundle:Branch')->findAll();
        //Prepare resum for all branch
        $totalSale = null;
        $totalProfit = null;
        $totalExpenditure = null;
        $totalBalance = null;

        foreach ($branches as $b){
            //Hydrate every branch
            $statisticHandler->setBranchFlyData($b);
            $totalSale = $totalSale + $b->getFlySaleAmount();
            $totalExpenditure = $totalExpenditure + $b->getFlyExpenditureAmount();
            $totalProfit = $totalProfit + $b->getFlyProfitAmount();
            $totalBalance = $totalBalance + $b->getFlyBalanceAmount();
        }

        //Get all the sale transaction amount for every month
        $stransactions = $statisticHandler->getSaleByMonth();
        /*//Get the resum for all branches
        $totalSale = $statisticHandler->getSale();
        $totalProfit = $statisticHandler->getProfit();
        $totalExpenditure = $statisticHandler->getExpenditure();
        $totalBalance = $statisticHandler->getBalance();*/

        return $this->render('/admin/vendor_dashboard.html.twig', array('stransactions' => $stransactions,
                                                                        'branches' => $branches,
                                                                        'totalSale' => $totalSale,
                                                                        'totalProfit' => $totalProfit,
                                                                        'totalBalance' => $totalBalance,
                                                                        'totalExpenditure' => $totalExpenditure,));
    }
    
    public function branchesAction()
    {
        $branches = $this->getDoctrine()->getManager()->getRepository('KmBundle:Branch')->findAll();
        return $this->render('KmBundle:Default:branches.html.twig', array('branches' => $branches));
    }
    
    public function validateUpdateStockAction($update)
    {
        $em = $this->getDoctrine()->getManager();
        //Case of stockage
        if($update == 1){
            $stocked = $em->getRepository('TransactionBundle:Stock')->findBy(array('stocked' => true));
            foreach ($stocked as $stock){
                $stock->setStocked(false);
            }
        }elseif($update == 0){
            $destocked = $em->getRepository('TransactionBundle:Stock')->findBy(array('destocked' => true));
            foreach ($destocked as $stock){
                $stock->setDestocked(false);
            }
        }else{
            $canceledSTransactions = $em->getRepository('TransactionBundle:CanceledSTransaction')->findAll();
            foreach ($canceledSTransactions as $object){
                $em->remove($object);
            }
        }
        
        $em->flush();
        
        return $this->redirect($this->generateUrl('transaction_pos_barcode'));
    }
    
    public function reportAAction()
    {
        //return $this->render('/pages/tables.html.twig');
        //return $this->render('/pages/form.html.twig');
        return $this->render('TransactionBundle:Default:report_a.html.twig');
        //return $this->render('TransactionBundle:Default:reciep_a4.html.twig');
    }
    
    public function reportBAction()
    {
        return $this->render('TransactionBundle:Default:report_b.html.twig');
    }
    
    public function settingAction()
    {
        return $this->render('/pages/setting.html.twig');
    }
    
    public function BarcodeTestAction()
    {
        //Get the product from the DB in order to send it to the view
        $em = $this->getDoctrine()->getManager();
        //Get all the products
        $products = $em->getRepository('TransactionBundle:Product')->findBy(array('locked' => false));
        
        return $this->render('TransactionBundle:Default:barecode_test.html.twig', array('products' => $products));
    }
    
    public function indexAction($barcode)
    {
        //Get the product from the DB in order to send it to the view
        $em = $this->getDoctrine()->getManager();
        
        $product = $em->getRepository('TransactionBundle:Product')->findOneBy(array('barcode' => $barcode));
        if(!$product){
            throw $this->createNotFoundException('product of barcode: '.$barcode.' does not exist in DB.');
        }
        $im = imagecreatefromstring($this->getImage($barcode));
        
        imagepng($im, getcwd().'/barcode/'.$barcode.'.png');
        
        return $this->render('TransactionBundle:Default:barecode_list.html.twig', array('barecode' => $barcode,
                                                                                        'product' => $product));  
    }
    
    public function getBarCodeAction($code)
    {
        $barcode = $this->get('hackzilla_barcode');
        $barcode->setMode(Barcode::MODE_PNG);
        
        $headers = array(
            'Content-Type' => 'image/png',
            'Content-Disposition' => 'inline; filename="'.$code.'.png"'
        );
        
        //return new Response($code);
        return new Response($barcode->outputImage($code), 200, $headers);
    }
    
    /**
     * Return image in a zip
     */
    public function barcodeZipAction($code)
    {
        $isbns = array(
            '978085934063',
            '500015941539',
            '978085956063',
            '500015921539',
        );

        $zipDir = sys_get_temp_dir();

        if (substr($zipDir, -1) !== '/') {
            $zipDir .= '/';
        }

        $zip = new \ZipArchive();
        $zipName = 'barcodes-' . time() . ".zip";
        $zip->open($zipDir . $zipName, \ZipArchive::CREATE);

        foreach ($isbns as $i => $isbn) {
            $barcode = \trim($isbn);
            $zip->addFromString($barcode . '.png', $this->getImage($barcode));
        }

        $zip->close();

        $response = new Response();
        $response->setContent(readfile($zipDir . $zipName));
        $response->headers->set('Content-Type', 'application/zip');
        $response->headers->set('Content-disposition', 'attachment; filename="' . $zipName . '"');
        $response->headers->set('Content-Length', filesize($zipDir . $zipName));

        return $response;
    }

    private function getImage($ean)
    {
        ob_start();

        $barcodeGenerator = new Barcode();
        $barcodeGenerator->setMode(Barcode::MODE_PNG);
        $barcodeGenerator->outputImage($ean);

        $contents = ob_get_clean();

        return $contents;
    }
}

src/KmBundle/Resources/views/Default/alert_stock.html.twig
<link rel="stylesheet" href="{{ asset('css/AdminLTE.min.css') }}">
{% if is_granted('ROLE_ADMIN') %}
    {% for branch in branches %}

<li class="dropdown notifications-menu">
    {% if branch.alertStocks|length > 0 %}
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-database"></i>
            <span class="badge bg-red">{{ branch.alertStocks|length }}</span>
        </a>
    {% else %}
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-database"></i>
            <span class="badge bg-green">!</span>
        </a>
    {% endif %}
    <ul class="dropdown-menu">
      <li>
        <!-- Inner Menu: contains the notifications -->
        <ul class="menu">
          {% for alertStock in branch.alertStocks|sortbyfield('value') %}
              <li>
                    <a href="{{ path('admin_transaction_stock_edit', {'id': alertStock.id}) }}">
                        {% if alertStock.value <= 0 %}
                            
                                <style>
                                        .myBlink{
                                            animation: blinker 3s linear infinite;
                                        }

                                        @keyframes blinker{
                                            50% {opacity: 0;}
                                        }
                                </style> 
                            
                            <span  {% if alertStock.value != 0 %}class="myBlink"{% endif %}>
                                
                                <span class="badge bg-red">{{ alertStock.value }}</span>
                                
                                <span {% if alertStock.value != 0 %}style="font-size: 14px; font-weight: bold; text-decoration: blink; color: red;"{% endif %}>{{ alertStock.product }} </span>
                                <br>
                                <span class="time"  style="padding-left: 5px; font-style: italic;">{{ alertStock.alertStockCreatedAt|ago }}</span>
                            </span>
                        {% elseif alertStock.value <= 2 %}
                            <span class="badge bg-orange">{{ alertStock.value }}</span>
                            <span>
                                <span style="font-size: 14px;"> {{ alertStock.product }} </span><br>
                              <span class="time">{{ alertStock.alertStockCreatedAt|ago }}</span>
                            </span>
                        {% else %}
                            <span class="badge bg">{{ alertStock.value }}</span>
                            <span>
                              <span style="font-size: 14px;"> {{ alertStock.product }} </span><br>
                              <span class="time">{{ alertStock.alertStockCreatedAt|ago }}</span>
                            </span>
                        {% endif %}
                  </a>
                </li>
           {% endfor %}
          
          
          <!-- end notification -->
        </ul>
      </li>
      <li class="footer"><a href="#"><span style="font-weight: bold;">{{ branch }}</span></a></li>
    </ul>
</li>
{% endfor %}
{% endif %}
<!--<li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
        <i class="fa fa-database"></i>
        <span class="badge bg-green">!</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">

    </ul>
</li>-->

<!--<li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
        <i class="fa fa-warning"></i>
        <span class="badge bg-orange">3</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">

    <li>
      <a>
        <span class="badge">-3</span>
        <span>
            <span style="font-size: 14px;">RAM format A4 </span><br>
            <span><i>- BATA -</i></span>
          <span class="time">45 mins ago</span>
        </span>
      </a>
    </li>
    <li>
      <a>
        <span class="badge">-1</span>
        <span>
          <span style="font-size: 14px;">Casque MP3 </span><br>
          <span><i>- VALLEY -</i></span>
          <span class="time">1 day ago</span>
        </span>
      </a>
    </li>
    <li>
      <div class="text-center">
        <a>
          <strong>All - BATA</strong>
          <i class="fa fa-angle-right"></i>
        </a>
      </div>
    </li>

  </ul>
                    
</li>-->

src/KmBundle/Resources/views/Default/branches.html.twig
{% for branch in branches %}
    <li>
        <a href="#level2_1">{{ branch.name }}</a>
    </li>
{% endfor %}

src/KmBundle/Resources/views/Default/front.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BeezyManager</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('assets/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('assets/css/custom.min.css') }}" rel="stylesheet">
    <link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
                <img src="{{ asset('images/logo.png') }}" style="width: 150px; height: 135px; margin-bottom: 23px;" />
                </br>
              <div class="row top_tiles">
              <a href="{{ path('transaction_pos_barcode') }}">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-8">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-cart-plus"></i></div>
                  <div class="count">POS 1</div>
                  
                </div>
              </div>
              </a>
              <a href="{{ path('transaction_pos2') }}">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-8">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-cart-plus"></i></div>
                  <div class="count">POS 2</div>
                  
                </div>
              </div>
              </a>
              <a href="{{ path('admin_transaction_stransaction_create') }}">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-8">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-cart-plus"></i></div>
                  <div class="count">POS 3</div>
                  
                </div>
              </div>
              </a>
              <a href="#">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-8">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-cart-plus"></i></div>
                  <div class="count" style="color: #bab8b8;">SOON </div>
                  
                </div>
              </div>
              </a>
            {% if (is_granted('ROLE_ADMIN')) %}
              <a href="{{ path('sonata_admin_dashboard') }}">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-bars"></i></div>
                  <div class="count">D 1</div>
                 
                </div>
              </div>
              </a>
              <a href="{{ path('km_dashboard') }}">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-line-chart"></i></div>
                  <div class="count">D 2</div>
                 
                </div>
              </div>
              </a>
              <a href="#">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-bars"></i></div>
                  <div class="count" style="color: #bab8b8;">SOON</div>
                 
                </div>
              </div>
              </a>
              <a href="#">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-bars"></i></div>
                  <div class="count" style="color: #bab8b8;">SOON</div>
                 
                </div>
              </div>
              </a>
            {% endif %} 
            </div>
            <hr>
                <span style="color: white;">©</span>
              <a href="#" style="color: white;"> 2017 - Saint-Cyr MAPOUKA</a>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{{ asset('assets/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('assets/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('assets/vendors/nprogress/nprogress.js') }}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('assets/js/custom.min.js') }}"></script>
  </body>
</html>

src/KmBundle/Resources/views/Default/translation.html.twig
<html>
    <body>
       {{ 'Hello'|trans }}  {{ name }}
    </body>
</html>