src/TransactionBundle/Entity/Product.php
<?php

namespace TransactionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="TransactionBundle\Repository\ProductRepository")
 * @UniqueEntity("barcode", message="this barcode has been already used")
 * @UniqueEntity("name", message="this name has been already used")
 * @ORM\HasLifecycleCallbacks
 */
class Product
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * Unmapped property to handle file uploads
     */
    private $file;
    
    /**
     * @var string
     *
     * @ORM\Column(name="updated", type="datetime", nullable=true)
     */
    private $updated;
    
    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, unique=false, nullable=true)
     */
    private $image;
    
    private $flyProfit;
    
    private $flyAmount;
    
    /**
     * @ORM\OneToMany(targetEntity="Stock", mappedBy="product")
     */
    private $stocks;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, unique=true)
     */
    private $name;
    
    /**
     * @var string
     *
     * @ORM\Column(name="projectCode", type="string", length=255, unique=false)
     */
    private $projectCode;

    /**
     * @var string
     *
     * @ORM\Column(name="officeCode", type="string", length=255, unique=true, nullable=true)
     */
    private $officeCode;
    
    /**
     * @var string
     *
     * @ORM\Column(name="linCode", type="string", length=255, unique=false, nullable=true)
     */
    private $linCode;
    
    /**
     * @var string
     *
     * @ORM\Column(name="locked", type="boolean", nullable=true)
     */
    private $locked;
    
    /**
     * @var string
     *
     * @ORM\Column(name="imagePos", type="boolean", nullable=true)
     */
    private $imagePos;
    
    /**
     * @var string
     *
     * @ORM\Column(name="barcode", type="string", length=255, nullable=true, unique=true)
     */
    private $barcode;
    
    /**
     * @var float
     *
     * @ORM\Column(name="unitPrice", type="float", nullable=true)
     */
    private $unitPrice;
    
    /**
     * @ORM\ManyToMany(targetEntity="TransactionBundle\Entity\Category", mappedBy="products")
     * @ORM\JoinColumn(nullable=true)
     */
    private $categories;
    
    /**
     * @var float
     *
     * @ORM\Column(name="WholeSalePrice", type="float", nullable=true)
     */
    private $wholeSalePrice;
    
    public function __toString() {
        if(!$this->name){
            return 'new Product';
        }
        
        return $this->name;
    }
    
    public function getProfit()
    {
        return $this->getUnitPrice() - $this->getWholeSalePrice();
    }
    
    /**
    * Sets file.
    *
    * @param UploadedFile $file
    */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
    * Get file.
    *
    * @return UploadedFile
    */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function lifecycleFileUpload()
    {
        $this->upload();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function refreshUpdated()
    {
        $this->setUpdated(new \DateTime());
    }
    
    /**
     * @ORM\PreRemove()
     */
    public function removeUPdate()
    {
        //Check whether the file exists first
        if (file_exists(getcwd().'/upload/product/'.$this->getImage())){
            //Remove it
            @unlink(getcwd().'/upload/product/'.$this->getImage());
            
        }
        
        return;
    }
    
    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }
        // move takes the target directory and target filename as params
        $this->getFile()->move(getcwd().'/upload/product', $this->getId().'.'.$this->getFile()->guessExtension());
        // clean up the file property as you won't need it anymore
        $this->setFile(null);
    }
    
    /**
     * Set image
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @param string $image
     *
     * @return PrDependentCandidate
     */
    public function setImage($image)
    {
        if($this->getFile() !== null){
            $this->image = $this->getFile()->guessExtension();
        }
        
        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        if((substr($this->image, -4) == 'jpeg')||(substr($this->image, -3) == 'jpg')||(substr($this->image, -3) == 'png')){
            return $this->getId().'.'.$this->image;
        }else{
            return null;
        }
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return PrParty
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function totalStock()
    {
        $total = 0;
        
        foreach ($this->getStocks() as $stock){
            $total = $total + $stock->getValue();
        }
        
        return $total;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set unitPrice
     *
     * @param float $unitPrice
     *
     * @return Product
     */
    public function setUnitPrice($unitPrice = null)
    {
        $this->unitPrice = $unitPrice;

        return $this;
    }

    /**
     * Get unitPrice
     *
     * @return float
     */
    public function getUnitPrice()
    {
        return $this->unitPrice;
    }

    /**
     * Set barcode
     *
     * @param string $barcode
     *
     * @return Product
     */
    public function setBarcode($barcode)
    {
        $this->barcode = $barcode;

        return $this;
    }

    /**
     * Get barcode
     *
     * @return string
     */
    public function getBarcode()
    {
        return $this->barcode;
    }

    /**
     * Set wholeSalePrice
     *
     * @param float $wholeSalePrice
     *
     * @return Product
     */
    public function setWholeSalePrice($wholeSalePrice = null)
    {
        $this->wholeSalePrice = $wholeSalePrice;

        return $this;
    }

    /**
     * Get wholeSalePrice
     *
     * @return float
     */
    public function getWholeSalePrice()
    {
        return $this->wholeSalePrice;
    }
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->stocks = new \Doctrine\Common\Collections\ArrayCollection();
        $this->categories = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add stock
     *
     * @param \TransactionBundle\Entity\Stock $stock
     *
     * @return Product
     */
    public function addStock(\TransactionBundle\Entity\Stock $stock)
    {
        $this->stocks[] = $stock;

        return $this;
    }

    /**
     * Remove stock
     *
     * @param \TransactionBundle\Entity\Stock $stock
     */
    public function removeStock(\TransactionBundle\Entity\Stock $stock)
    {
        $this->stocks->removeElement($stock);
    }

    /**
     * Get stocks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStocks()
    {
        return $this->stocks;
    }

    /**
     * Set locked
     *
     * @param boolean $locked
     *
     * @return Product
     */
    public function setLocked($locked)
    {
        $this->locked = $locked;

        return $this;
    }

    /**
     * Get locked
     *
     * @return boolean
     */
    public function isLocked()
    {
        return $this->locked;
    }

    /**
     * Get locked
     *
     * @return boolean
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Set imagePos
     *
     * @param boolean $imagePos
     *
     * @return Product
     */
    public function setImagePos($imagePos)
    {
        $this->imagePos = $imagePos;

        return $this;
    }

    /**
     * Get imagePos
     *
     * @return boolean
     */
    public function getImagePos()
    {
        return $this->imagePos;
    }

    /**
     * Set flyProfit
     *
     * @param string $flyProfit
     *
     * @return Product
     */
    public function setFlyProfit($flyProfit)
    {
        $this->flyProfit = $flyProfit;

        return $this;
    }

    /**
     * Get flyProfit
     *
     * @return string
     */
    public function getFlyProfit()
    {
        return $this->flyProfit;
    }

    /**
     * Set flyAmount
     *
     * @param string $flyAmount
     *
     * @return Product
     */
    public function setFlyAmount($flyAmount)
    {
        $this->flyAmount = $flyAmount;

        return $this;
    }

    /**
     * Get flyAmount
     *
     * @return string
     */
    public function getFlyAmount()
    {
        return $this->flyAmount;
    }

    /**
     * Add category
     *
     * @param \TransactionBundle\Entity\Category $category
     *
     * @return Product
     */
    public function addCategory(\TransactionBundle\Entity\Category $category)
    {

src/TransactionBundle/Controller/DefaultController.php
<?php

namespace TransactionBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function wayBillAction()
    {
        return $this->render('TransactionBundle:Default:way_bill.html.twig');
    }
    
    public function saleAction(Request $request)
    {
        //Get the data structure that came from the client as an array
        $data = json_decode($request->getContent(), true);
        //Get the sale handler service
        $saleHandler = $this->get('transaction.sale_handler');
        //Process the sale transaction
        /*@Saint-Cyr NOTICE: because it is the Starter formular, we just manager one branch but we still have the right DB schema in order
         * to keep compatibility with other formula so that when a customer want to upgrade, it make it easy for us. And we consider as
         * one branch the the very first one in the database also we'll make sure the prevent other registration of any other branch
         */
        //$mainBranch = $this->getDoctrine()->getManager()->getRepository('KmBundle:Branch')->find(1);
        //Get the user in order to get it related branch and use it 
        $user = $this->getUser();
        if(!$user){
            $this->createNotFoundException("User not found.");
        }
        
        $branch = $user->getBranch();
        $saleHandler->processSaleTransaction($data, $branch);
        
        $response = new Response('Successfull transaction');
                            
        $response->headers->set('Access-Control-Allow-Origin', 'http://localhost');
        
        return $response;
    }
    
    public function posAction()
    {
        //Get the entity manager
        $em = $this->getDoctrine()->getManager();
        //Get the list of all the products
        $products = $em->getRepository('TransactionBundle:Product')->findAll();
        
        return $this->render('TransactionBundle:POS:pos.html.twig', array('products' => $products));
    }
    
    public function pos2Action()
    {
        //Get the entity manager
        $em = $this->getDoctrine()->getManager();
        //Get the list of all the products
        $products = $em->getRepository('TransactionBundle:Product')->findAll();
        //Get the list of all the categories
        $categories = $em->getRepository('TransactionBundle:Category')->findAll();

        return $this->render('TransactionBundle:POS:pos2.html.twig', array('categories' => $categories,
                                                                           'products' => $products));
    }
    
    public function productListAction()
    {
        //Get the entity manager
        $em = $this->getDoctrine()->getManager();
        //Get the products list
        $product = $em->getRepository('TransactionBundle:Product')->find(1);
        $data = '<button class="buttons btn btn-primary" ng-click="add('.$product->getId().')">'.$product->getName().'</button>';
        return new Response($data);
    }
}

src/TransactionBundle/Resources/views/Default/barecode_list.html.twig
<link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
<img src="{{ asset('images/logo.png') }}" style="width: 100px; float: left;" />
<span style="color: #320070; font-size: 12px; margin-left: 24px;">Generated on {{ "now"|date('m/d/Y H:i:s') }}</span>
<span style="color: #320070; font-size: 12px; margin-left: 230px;">© 2017 - Saint-Cyr MAPOUKA</span>
<hr>
<img src="{{ asset('upload/product/'~product.image) }}" style="width: 110px; height: 90px; margin-left: 173px; margin-bottom: 0px;" />    
<h3 style="margin-left: 265px; color: #5e388f; "> {{ product.name }} </h3>

{% for i in 0..35 %}
    {% if i % 3 == 0 %}
        <hr>
    {% endif %}
    <img src="{{ asset('barcode/'~barecode~'.png') }}"  />
{% endfor %}
<hr>

src/TransactionBundle/Resources/views/Default/barecode_test.html.twig
<link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
<img src="{{ asset('images/logo.png') }}" style="width: 100px; float: left;" />
<span style="color: #320070; font-size: 12px; margin-left: 24px;">Generated on {{ "now"|date('m/d/Y H:i:s') }}</span>
<span style="color: #320070; font-size: 12px; margin-left: 230px;">© 2017 - Saint-Cyr MAPOUKA</span>
<hr>
<img src="{{ asset('image/logo.png') }}" style="width: 100px; height: 150px; margin-left: 173px; margin-bottom: 0px;" />    
<h3 style="margin-left: 265px; color: #5e388f; "> BeezyManager </h3>
<table style="width 100%">
{% for p in products %}
        
    {% if loop % 3 == 0 %}
        <br>
    {% endif %}
    {{ p.name }}
    <img src="{{ asset('barcode/'~p.barcode~'.png') }}"  />
{% endfor %}
</table>
<hr>

src/TransactionBundle/Resources/views/Default/list.html.twig
<td>
    {% if (object.barcode) %}
        <a href="{{ path('km_homepage', {'barcode':object.barcode}) }}" target="_blank">
            {% if object.image == "" %}
                <img src="{{ asset('/images/logo.png') }}" alt="{{ object.name }}" style="width: 85px; height: 65px;"/>
            {% else %}
                <img src="{{ asset('upload/product/'~object.image) }}" alt="{{ object.name }}" style="width: 85px; height: 65px;"/>
            {% endif %}
        </a>
    {% else %}
        <img src="{{ asset('upload/product/'~object.image) }}" alt="{{ object.name }}" style="width: 85px; height: 65px;"/>
    {% endif %}
</td>

src/TransactionBundle/Resources/views/Default/reciep_a4.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BeezyManager</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('assets/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    
    <!-- Custom styling plus plugins -->
    
    <link rel="stylesheet" href="{{ asset('css/AdminLTE.min.css') }}">
    <link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
  </head>


<body onload="window.print();">
<div class="wrapper">
  <!-- Main content -->
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      
      <div class="col-xs-12">
        <h2 class="page-header">
          <img src="{{ asset('images/1.gif') }}" style="width: 100%; height: 100px; padding-top: -2px;"/>
        </h2>
      </div>
      <!-- /.col -->
    </div>
    
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col">
        From
        <address>
          <strong>Admin, Inc.</strong><br>
        </address>
      </div>
      <!-- /.col -->
      <div class="col-sm-4 invoice-col">
        To
        <address>
          <strong>John Doe</strong><br>
         
        </address>
      </div>
      <!-- /.col -->
      <div class="col-sm-4 invoice-col">
        <b>Invoice #007612</b><br>
        <br>
        
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-xs-12 table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Qty</th>
            <th>Product</th>
            <th>Serial #</th>
            <th>Description</th>
            <th>Subtotal</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>1</td>
            <td>Call of Duty</td>
            <td>455-981-221</td>
            <td>El snort testosterone trophy driving gloves handsome</td>
            <td>$64.50</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Need for Speed IV</td>
            <td>247-925-726</td>
            <td>Wes Anderson umami biodiesel</td>
            <td>$50.00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Monsters DVD</td>
            <td>735-845-642</td>
            <td>Terry Richardson helvetica tousled street art master</td>
            <td>$10.70</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Grown Ups Blue Ray</td>
            <td>422-568-642</td>
            <td>Tousled lomo letterpress</td>
            <td>$25.99</td>
          </tr>
          
          </tbody>
        </table>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
      <!-- accepted payments column -->
      <div class="col-xs-6">

        <p class="text-muted well well-sm no-shadow" style="margin-top: 10px; font-style: italic;">
        	&ldquo;  Thank you for doing business with us ! Look forward to see you next time.&rdquo;
        </p>
        <img src="{{ asset('images/3.jpg') }}" style="width: 300px; padding-bottom: -12px;" />
        <h2 style="padding-top: 12px; padding-left: 80px; text-decoration: underline;">The Seller</h2>
      </div>
      <!-- /.col -->
      <div class="col-xs-6">

        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:50%">Subtotal:</th>
              <td>$250.30</td>
            </tr>
            <tr>
              <th>Tax (9.3%)</th>
              <td>$10.34</td>
            </tr>
            <tr>
              <th>Shipping:</th>
              <td>$5.80</td>
            </tr>
            <tr>
              <th>Total:</th>
              <td>$265.24</td>
            </tr>
          </table>
        </div>
        <img src="{{ asset('images/31.png') }}" style="padding-top: 20px; padding-left: 80px;"/>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
<!-- ./wrapper -->
</body>
</html>

src/TransactionBundle/Resources/views/Default/report_b.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BeezyManager</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('assets/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    
    <!-- Custom styling plus plugins -->
    <link href="{{ asset('assets/css/custom.min.css') }}" rel="stylesheet">
    <link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        
          {% if(is_granted('ROLE_SUPER_ADMIN')) %}
          {% include 'admin/sidebar_vendor.html.twig' %}
          {% endif %}
          {% include 'admin/topnav.html.twig' %}

        

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Sale transaction Report <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <section class="content invoice">
                      <!-- title row -->
                      <div class="row">
                        <div class="col-xs-12 invoice-header">
                          
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- info row -->
                      
                      <!-- /.row -->

                      <!-- Table row -->
                      <div class="row">
                        <div class="col-xs-12 table">
                          <table class="table table-striped">
                            <thead>
                              <tr>
                                <th>Qty</th>
                                <th>Product</th>
                                <th>Sale (FCFA)</th>
                                {% if(is_granted('ROLE_SUPER_ADMIN')) %}
                                <th>Profit (FCFA)</th>
                                {% endif %}
                                <th>Transaction ID#</th>
                                <th>Seller</th>
                                <!--<th style="width: 59%">Description</th>-->
                              </tr>
                            </thead>
                            <tbody>
                              
                              {% for st in saleTransactions %}
                               {% for sale in st.sales %}
                               <tr>
                                <td>{{ sale.quantity }}</td>
                                <td>{{ sale.product }}</td>
                                <td>{{ sale.amount }}</td>
                                {% if(is_granted('ROLE_SUPER_ADMIN')) %}
                                <td>{{ sale.profit }}</td>
                                {% endif %}
                                <td>{{ sale.stransaction.id }}</td>
                                <td>
                                    {% if sale.stransaction.user is empty %}
                                        Unknown
                                        {% else %}
                                          {{ sale.stransaction.user.name }}  
                                    {% endif %}
                                </td>
                              </tr>
                              {% endfor %}
                                  {% endfor %}
                              
                            </tbody>
                          </table>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <div class="row">
                        <!-- accepted payments column -->
                       
                        <!-- /.col -->
                        <div class="col-xs-6">
                          <p class="lead">Resume</p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody style="font-size: 15px; color: black;">
                                <tr>
                                  <th>Total Sale (FCFA):</th>
                                  <td>{{ totalSaleAmount }}</td>
                                </tr>
                                {% if(is_granted('ROLE_SUPER_ADMIN')) %}
                                <tr>
                                  <th>Total Profit (FCFA):</th>
                                  <td style="font-size: 15px; color: green;">{{ totalProfit }}</td>
                                </tr>
                                {% endif %}
                                <tr>
                                  <th>Transaction number:</th>
                                  <td style="font-size: 15px; color:black;">{{ saleTransactions|length }}</td>
                                </tr>
                                
                              </tbody>
                            </table>
                          </div>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- this row will not appear when printing -->
                      
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{{ asset('assets/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('assets/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('assets/vendors/nprogress/nprogress.js') }}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('assets/js/custom.min.js') }}"></script>
  </body>
</html>